apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec: # spec of deployment
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: server-pod
      labels:
        app: server #This must be the same as the deployment label.
    spec: # Spec of Pod
      containers:
        - name: server
          image: laithharb/server:v1
---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30005